import React from 'react';
import ReactDOM from 'react-dom/client';
import {RouterProvider} from 'react-router-dom';
import {QueryClientProvider} from '@tanstack/react-query';
import {queryClient} from './app/queryClient';
import {router} from './app/router';
import './styles/index.css';
import './styles/venture.css';
import {ProviderKeysDialog} from './components/ProviderKeysDialog';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><QueryClientProvider client={queryClient}><ProviderKeysDialog/><RouterProvider router={router}/></QueryClientProvider></React.StrictMode>);
